Routine bugs corretion

diff --git a/setPasswordSubnet b/setPasswordSubnet
--- a/setPasswordSubnet
+++ b/setPasswordSubnet
@@ -3,10 +3,20 @@
 
 #
 #
-# setPassworuSubnet v 1.1
+# setPassworuSubnet v 1.2
 # Set the customized passwords on system
 # Author ACS 2014
 
+PROGNAME=${0##*/}
+VERSION="1.2"
+
+## Parse prog name to find an ID if executed from SPOTDB
+
+ID=$(echo $PROGNAME | awk -F "_" '{print $3}')
+
+## Global Variables
+
+typeset APISERVER="x.x.x.204" # IP address of the api server
 
 
 log() {
@@ -26,10 +36,10 @@ log() {
   else
     echo "$line"
   fi >&2
-  
+  URI="http://$APISERVER/SPOT/provisioning/api/events"
   REST='{"title":"setPasswordssubnet ","content":"'$line'","userid":"'`whoami`'","date":"'`date`'"}'
   (
-perl - "$REST"   <<'_HERE_'
+perl - "$REST" "$URI"  <<'_HERE_'
                                  use integer;
                                  use POSIX qw(strftime);
                                  use Backticks;
@@ -48,8 +58,8 @@ perl - "$REST"   <<'_HERE_'
                                  use HTTP::Request;
                                  use LWP;
                                  use File::Path qw{mkpath};
-                                 my $uri = "http://x.x.x.204/SPOT/provisioning/api/events";
                                  my $REST = shift;
+				 my $uri = shift;
                                  my $lwp = LWP::UserAgent->new(
                                                  timeout               => 10,
                                                  );
@@ -66,9 +76,10 @@ _HERE_
 sendToTable() {
   htmlTable=`echo $htmlTable | tr -d '\n\r'`
   TIME=`date +'%F %T'`
+  URI="http://$APISERVER/SPOT/provisioning/api/tblpassword/$salesorder"
   REST='{"salesorder":"'$salesorder'","results":"'$htmlTable'","time":"'$TIME'"}'
   (
-perl - "$REST"  "$salesorder"  <<'_HERE_'
+perl - "$REST"  "$URI" <<'_HERE_'
                                  use integer;
                                  use POSIX qw(strftime);
                                  use Backticks;
@@ -88,8 +99,7 @@ perl - "$REST"  "$salesorder"  <<'_HERE_'
                                  use LWP;
                                  use File::Path qw{mkpath};
                                  my $REST = shift;
-                                 my $salesorder = shift;
-                                 my $uri = "http://x.x.x.204/SPOT/provisioning/api/tblpassword/$salesorder";
+                                 my $uri = shift;
                                  my $lwp = LWP::UserAgent->new(
                                                  timeout               => 10,
                                                  );
@@ -164,13 +174,13 @@ sshExe() {
 aixPassword () {
   aix_cmd=" uname -L | cut -d' ' -f2 && exit"
   log WARN "Aix function hostname $host_name"
-  Sn=`sshExe $host "$aix_cmd"`
+  Sn=$(sshExe $host "$aix_cmd")
   comments=$Sn
-  line=`cat /tmp/pass.$random`
+  line=$(cat /tmp/pass.$random)
   OS="Unix"
   for t in $line; do
-    user=`echo $t | awk -F ":" '{print $1}'`
-    password=`echo $t | awk -F ":" '{print $2}'`
+    user=$(echo $t | awk -F ":" '{print $1}')
+    password=$(echo $t | awk -F ":" '{print $2}')
     if [[ "$user"  =~ "root" ]]; then
       password_root=$password
       client_pass="$oldroot"
@@ -180,10 +190,10 @@ aixPassword () {
     tblpass=$password
     log INFO "About to change password on a AIX server"
     ret=""
-    ret=`sshpass -p $client_pass  $ssh  root@$host "id -u $user 2>&1 >/dev/null &&  echo 'EXISTS' || echo 'ERROR'"`
+    ret=$(sshpass -p $client_pass  $ssh  root@$host "id -u $user 2>&1 >/dev/null &&  echo 'EXISTS' || echo 'ERROR'")
     log WARN "The return value if $user exist is: $ret"
     if [[ "$ret" == "EXISTS"  || "$ret" == "" ]]; then
-      `sshpass -p $client_pass  $ssh  root@$host "echo $t | chpasswd  -c 2>&1 /dev/null"`
+      $(sshpass -p $client_pass  $ssh  root@$host "echo $t | chpasswd  -c 2>&1 /dev/null")
       if [ $? -eq 0 ]; then
         tableMiddle
       fi
@@ -194,13 +204,13 @@ aixPassword () {
 linPassword () {
   linux_cmd=" dmidecode -s system-serial-number | grep -v \"\#\""
   #  host_name=`sshExe $host hostname`
-  Sn=`sshExe $host "$linux_cmd 2>/dev/null"`
+  Sn=$(sshExe $host "$linux_cmd 2>/dev/null")
   comments=$Sn
-  line=`cat /tmp/pass.$random`
+  line=$(cat /tmp/pass.$random)
   OS="Unix"
   for t in $line; do
-    user=`echo $t | awk -F ":" '{print $1}'`
-    password=`echo $t | awk -F ":" '{print $2}'`
+    user=$(echo $t | awk -F ":" '{print $1}')
+    password=$(echo $t | awk -F ":" '{print $2}')
     if [[ "$user"  =~ "root" ]]; then
       password_root=$password
       client_pass="$oldroot"
@@ -211,11 +221,11 @@ linPassword () {
     #Password need to apply dinamically because we use ssh
     log INFO "About to change password on a Linux server"
     ret=""
-    ret=`sshpass -p $client_pass  $ssh  root@$host "id -u $user 2>&1 >/dev/null &&  echo 'EXISTS' || echo 'ERROR'"`
+    ret=$(sshpass -p $client_pass  $ssh  root@$host "id -u $user 2>&1 >/dev/null &&  echo 'EXISTS' || echo 'ERROR'")
     log WARN "The return value if $user exist is: $ret"
     if [[ "$ret" == "EXISTS"  || "$ret" == "" ]]; then
       
-      `sshpass -p $client_pass  $ssh  root@$host "echo $t | chpasswd  2>&1 /dev/null"`
+      $(sshpass -p $client_pass  $ssh  root@$host "echo $t | chpasswd  2>&1 /dev/null")
       if [ $? -eq 0 ]; then
         tableMiddle
       fi
@@ -228,20 +238,20 @@ linPassword () {
 
 
 winPassword () {
-  host_name=`nmblookup -A $host | grep '<00> -     '  | awk '{print $1}' | head -1`
+  host_name=$(nmblookup -A $host | grep '<00> -     '  | awk '{print $1}' | head -1)
   host_name=${host_name,,}
   log INFO "Customizing host $host_name , os $os"
-  Sn=`winexe  -U administrator%$oldroot //$host   "cmd /C wmic.exe bios get serialnumber <NUL:" | head -2 | tail -1`
+  Sn=$(winexe  -U administrator%$oldroot //$host   "cmd /C wmic.exe bios get serialnumber <NUL:" | head -2 | tail -1)
   comments=$Sn
-  line=`cat /tmp/pass.win.$random`
+  line=$(cat /tmp/pass.win.$random)
   OS="Windows"
   for t in $line; do
-    user=`echo $t | awk -F ":" '{print $1}'`
-    old_pass=`echo $t | awk -F ":" '{print $2}'`
-    new_pass=`echo $t | awk -F ":" '{print $3}'`
+    user=$(echo $t | awk -F ":" '{print $1}')
+    old_pass=$(echo $t | awk -F ":" '{print $2}')
+    new_pass=$(echo $t | awk -F ":" '{print $3}')
     tblpass=$new_pass
     log INFO "About tu run winexe -U $user%$old_pass //$host 'net user $user $new_pass'"
-    `winexe -U $user%$old_pass //$host "net user $user $new_pass" > /dev/null`
+    winexe -U $user%$old_pass //$host "net user $user $new_pass" > /dev/null
     if [ $? -eq 0 ]; then
       
       tableMiddle
@@ -371,16 +381,17 @@ do
       so="$2"
       shift 2
     ;;
+    -crmid )
+      system_id="$2"
+      shift 2
+    ;;
+
     -ip)
       ip="$2"
       shift 2
     ;;
     -netmask)
       netmask="$2"
-      shift 2
-    ;;
-    -crmid )
-      system_id=$2
       shift 2
     ;;
     *)      break
@@ -395,7 +406,7 @@ salesorder=`echo $so  | awk -F "|" '{print $1}'`
 
 
 technology=" "
-system_id="  "
+#system_id="  "
 customer=$customer
 region="  "
 phone="  "
@@ -433,8 +444,8 @@ host_name_ctrl="start_hosts mgt-ai fw01"
 port_list="514 17988 22 80 4899 5989"
 #CIDR=`mask2cdr $netmask`
 myhost_name="mgt-ai"
-NETWORK=` ipcalc $master_ip $netmask  | grep Network: | awk  '{print $2}'`
-all_host=`nmap -nsP $NETWORK 2>/dev/null | grep Nmap | awk '{print $5}' | grep -v address | grep -v http`
+NETWORK=$(ipcalc $master_ip $netmask  | grep Network: | awk  '{print $2}')
+all_host=$(nmap -nsP $NETWORK 2>/dev/null | grep Nmap | awk '{print $5}' | grep -v address | grep -v http)
 #Start loop on all host found on network
 for host in $all_host
 do
@@ -443,14 +454,14 @@ do
   if [[ !  "$master_ip" == "$host" && ! "$all_host" == "address" ]]; then
     #Check if AIX
     
-    if  [[ `nmap -p 514 $host  | grep open` && `nmap -p 513 $host  | grep open` && `nmap -p 512 $host  | grep open` ]]; then
+    if  [[ $(nmap -p 514 $host  | grep open) && $(nmap -p 513 $host  | grep open) && $(nmap -p 512 $host  | grep open) ]]; then
       log WARN "Detected AIX node"
-      NAME=`sshpass -p $PASSWORD $ssh  root@$host uname 2>/dev/null`
+      NAME=$(sshpass -p $PASSWORD $ssh  root@$host uname 2>/dev/null)
       #log WARN "NAME $NAME"
       if [[ "$NAME" =~ "AIX" ]]; then
-        host_name=`sshpass -p $PASSWORD $ssh root@$host hostname`
+        host_name=$(sshpass -p $PASSWORD $ssh root@$host hostname)
         if [ $? -eq 0 ]; then
-          already_done=`CheckHost $host_name`
+          already_done=$(CheckHost $host_name)
           if [[ ! "$already_done" == "1" &&  ! "$host_name" == $myhost_name ]]; then
             host_name_ctrl=$host_name_ctrl" "$host_name
             aixPassword
@@ -460,34 +471,34 @@ do
       #End AIX
       #Check if windows
       
-    elif  [[ `nmap -p 4899 $host | grep open` || `nmap -p 3389 -PN $host | grep open` ]];
+    elif  [[ $(nmap -p 4899 $host | grep open) || $(nmap -p 3389 -PN $host | grep open) ]];
     then
       log WARN "Detected Windows node"
-      host_name=`nmblookup -A $host | grep '<00> -     '  | awk '{print $1}'`
+      host_name=$(nmblookup -A $host | grep '<00> -     '  | awk '{print $1}')
       host_name=${host_name,,}
       #		echo $host_name "windows"
-      already_done=`CheckHost $host_name`
+      already_done=$(CheckHost $host_name)
       if [[ ! "$already_done" == "1" &&  ! "$host_name" == $myhost_name ]]; then
         host_name_ctrl=$host_name_ctrl" "$host_name
         winPassword
       fi
       #End Check Windows
       #Check if storwizev7000
-    elif  [[ `nmap -p 80 $host | grep open` && `nmap -p 5989 $host | grep open` ]];
+    elif  [[ $(nmap -p 80 $host | grep open) && $(nmap -p 5989 $host | grep open) ]];
     then
       log WARN "Detected Storwize SAN"
-      host_name=`$ssh_v7000 superuser@$host lssystemip 2>/dev/null | tail -1 | awk '{print $2}'`
-      already_done=`CheckHost $host_name`
+      host_name=$($ssh_v7000 superuser@$host lssystemip 2>/dev/null | tail -1 | awk '{print $2}')
+      already_done=$(CheckHost $host_name)
       if [[ ! "$already_done" == "1" &&  ! "$host_name" == $myhost_name ]]; then
         host_name_ctrl=$host_name_ctrl" "$host_name
-        Sn=`sshpass -p $PASSWORD $ssh  superuser@$host lsenclosure 2>/dev/null | tail -1 | awk '{print $8}'`
+        Sn=$(sshpass -p $PASSWORD $ssh  superuser@$host lsenclosure 2>/dev/null | tail -1 | awk '{print $8}')
         comments=$Sn
-        line=`cat /tmp/pass.v7000.$random`
+        line=$(cat /tmp/pass.v7000.$random)
         for i in $line; do
-          user=`echo $i | awk -F ":" '{print $1}'`
-          password=`echo $i | awk -F ":" '{print $2}'`
+          user=$(echo $i | awk -F ":" '{print $1}')
+          password=$(echo $i | awk -F ":" '{print $2}')
         done
-        return=`$ssh_v7000 $user@$host "chuser -password $password $user 2>&1 /dev/null; echo $?"`
+        return=$($ssh_v7000 $user@$host "chuser -password $password $user 2>&1 /dev/null; echo $?")
         if [ $return  -eq 0 ]; then
           OS="Network Equipment"
           tableMiddle
@@ -495,27 +506,27 @@ do
       fi
       #End Check Storwize v7000
       #Check if SAN switch (Brocade)
-    elif  [[ `nmap -p 80 $host | grep open` && `nmap -p 17988 $host | grep closed`  && `nmap -p 111 $host | grep closed` ]];
+    elif  [[ $(nmap -p 80 $host | grep open) && $(nmap -p 17988 $host | grep closed)  && $(nmap -p 111 $host | grep closed) ]];
     then
       log WARN "Detected San switch"
       host_name=$(TIMEOUT 3 "sshpass -p $PASSWORD $ssh admin@$host switchname")
       if [[ ! "$host_name" == "" ]];
       then
-        already_done=`CheckHost $host_name`
+        already_done=$(CheckHost $host_name)
         if [[ ! "$already_done" == "1" &&  ! "$host_name" == $myhost_name ]]; then
           host_name_ctrl=$host_name_ctrl" "$host_name
-          Sn=`sshpass -p $PASSWORD $ssh admin@$host chassisshow | tail -2 | head -1 | awk '{print $3}' `
+          Sn=$(sshpass -p $PASSWORD $ssh admin@$host chassisshow | tail -2 | head -1 | awk '{print $3}' )
           comments=$Sn
-          line=`cat /tmp/pass.$random`
+          line=$(cat /tmp/pass.$random)
           for i in $line; do
-            user=`echo $i | awk -F ":" '{print $1}'`
-            password=`echo $i | awk -F ":" '{print $2}'`
+            user=$(echo $i | awk -F ":" '{print $1}')
+            password=$(echo $i | awk -F ":" '{print $2}')
             if [[ "$user"  =~ "root" ]]; then
               password_root=$password
             fi
           done
           for user_on_switch in admin ; do
-            return=`sshpass -p $PASSWORD $ssh  $user_on_switch@$host "passwd $user_on_switch -old  $PASSWORD -new $password_root  2>&1 /dev/null; echo $?"`
+            return=$(sshpass -p $PASSWORD $ssh  $user_on_switch@$host "passwd $user_on_switch -old  $PASSWORD -new $password_root  2>&1 /dev/null; echo $?")
             if [ "$return" = "0" ]; then
               OS="Network Equipment"
               tableMiddle
@@ -525,10 +536,10 @@ do
       fi
       #End Brocade
       #Check if a Linux machine
-    elif [[ `nmap -p 22 $host | grep open` && `nmap -p 17988 $host | grep closed` && `nmap -p 3306 $host | grep closed` && `TIMEOUT 6 "sshpass -p $PASSWORD $ssh root@$host uname 2>/dev/null"` =~ "Linux" ]];
+    elif [[ $(nmap -p 22 $host | grep open) && $(nmap -p 17988 $host | grep closed) && $(nmap -p 3306 $host | grep closed) && $(TIMEOUT 6 "sshpass -p $PASSWORD $ssh root@$host uname 2>/dev/null") =~ "Linux" ]];
     then
       log WARN "Detected Linux host"
-      host_name=`sshpass -p $PASSWORD  $ssh root@$host hostname`
+      host_name=$(sshpass -p $PASSWORD  $ssh root@$host hostname)
       already_done=`CheckHost $host_name`
       if [[ ! "$already_done" == "1" &&  ! "$host_name" == $myhost_name  ]]; then
         host_name_ctrl=$host_name_ctrl" "$host_name
diff --git a/setPasswords b/setPasswords
--- a/setPasswords
+++ b/setPasswords
@@ -3,10 +3,20 @@
 
 #
 #
-# setPasswords v 1.1
+# setPasswords v 1.2
 # Set the customized passwords on system
 # Author ACS 2014
 
+PROGNAME=${0##*/}
+VERSION="0.1"
+
+## Parse prog name to find an ID if executed from SPOTDB
+
+ID=$(echo $PROGNAME | awk -F "_" '{print $3}')
+
+## Global Variables
+
+typeset APISERVER="x.x.x.204" # IP address of the api server
 
 
 log() {
@@ -26,10 +36,10 @@ log() {
   else
     echo "$line"
   fi >&2
-  
+  URI="http://$APISERVER/SPOT/provisioning/api/events"
   REST='{"title":"setPasswords ","content":"'$line'","userid":"'`whoami`'","date":"'`date`'"}'
   (
-perl - "$REST"   <<'_HERE_'
+perl - "$REST"   "$URI" <<'_HERE_'
 				 use integer;
 				 use POSIX qw(strftime);
 				 use Backticks;
@@ -48,8 +58,8 @@ perl - "$REST"   <<'_HERE_'
 				 use HTTP::Request;
 				 use LWP;
 				 use File::Path qw{mkpath};
-				 my $uri = "http://x.x.x.204/SPOT/provisioning/api/events";
 				 my $REST = shift;
+				 my $uri = shift;
 				 my $lwp = LWP::UserAgent->new(
 						 timeout               => 10,
 						 );
@@ -65,10 +75,10 @@ _HERE_
 sendToTable() {
   htmlTable=`echo $htmlTable | tr -d '\n\r'`
   TIME=`date +'%F %T'`
-  
+  URI="http://$APISERVER/SPOT/provisioning/api/tblpassword/$salesorder"
   REST='{"salesorder":"'$salesorder'","results":"'$htmlTable'","time":"'$TIME'"}'
   (
-perl - "$REST"  "$salesorder"  <<'_HERE_'
+perl - "$REST"  "$URI" <<'_HERE_'
                                  use integer;
                                  use POSIX qw(strftime);
                                  use Backticks;
@@ -88,8 +98,7 @@ perl - "$REST"  "$salesorder"  <<'_HERE_'
                                  use LWP;
                                  use File::Path qw{mkpath};
                                  my $REST = shift;
-				 my $salesorder = shift;
-				 my $uri = "http://x.x.x.204/SPOT/provisioning/api/tblpassword/$salesorder";
+				 my $uri = shift;
                                  my $lwp = LWP::UserAgent->new(
                                                  timeout               => 10,
                                                  );
@@ -155,15 +164,15 @@ sshExe() {
 
 aixPassword () {
   aix_cmd=" uname -L | cut -d' ' -f2"
-  host_name=`sshExe $host hostname`
+  host_name=$(sshExe $host hostname)
   if [ $? -eq 0 ]; then
-    Sn=`sshExe $host "$aix_cmd"`
+    Sn=$(sshExe $host "$aix_cmd")
     comments=$Sn
-    line=`cat /tmp/pass.$random`
+    line=$(cat /tmp/pass.$random)
     OS="Unix"
     for t in $line; do
-      user=`echo $t | awk -F ":" '{print $1}'`
-      password=`echo $t | awk -F ":" '{print $2}'`
+      user=$(echo $t | awk -F ":" '{print $1}')
+      password=$(echo $t | awk -F ":" '{print $2}')
       if [[ "$user"  =~ "root" ]]; then
         password_root=$password
         client_pass="$oldroot"
@@ -173,10 +182,10 @@ aixPassword () {
       tblpass=$password
       log INFO "About to change password on a AIX server, HOST: $host_name"
       ret=""
-      ret=`sshpass -p $client_pass  $ssh  root@$host "id -u $user 2>&1 >/dev/null &&  echo 'EXISTS' || echo 'ERROR'"`
+      ret=$(sshpass -p $client_pass  $ssh  root@$host "id -u $user 2>&1 >/dev/null &&  echo 'EXISTS' || echo 'ERROR'")
       log WARN "The return value if $user exist is: $ret"
       if [[ "$ret" == "EXISTS"  || "$ret" == "" ]]; then
-        `sshpass -p $client_pass  $ssh  root@$host "echo $t | chpasswd  -c 2>&1 /dev/null"`
+        sshpass -p $client_pass  $ssh  root@$host "echo $t | chpasswd  -c 2>&1 /dev/null"
         if [ $? -eq 0 ]; then
           tableMiddle
         fi
@@ -188,14 +197,14 @@ aixPassword () {
 
 linPassword () {
   linux_cmd=" dmidecode -s system-serial-number | grep -v \"\#\""
-  host_name=`sshExe $host hostname`
-  Sn=`sshExe $host "$linux_cmd 2>/dev/null"`
+  host_name=$(sshExe $host hostname)
+  Sn=$(sshExe $host "$linux_cmd 2>/dev/null")
   comments=$Sn
-  line=`cat /tmp/pass.$random`
+  line=$(cat /tmp/pass.$random)
   OS="Unix"
   for t in $line; do
-    user=`echo $t | awk -F ":" '{print $1}'`
-    password=`echo $t | awk -F ":" '{print $2}'`
+    user=$(echo $t | awk -F ":" '{print $1}')
+    password=$(echo $t | awk -F ":" '{print $2}')
     if [[ "$user"  =~ "root" ]]; then
       password_root=$password
       client_pass="$oldroot"
@@ -206,11 +215,11 @@ linPassword () {
     #Password need to apply dinamically because we use ssh
     log INFO "About to change password on a Linux server, HOST: $host_name"
     ret=""
-    ret=`sshpass -p $client_pass  $ssh  root@$host "id -u $user 2>&1 >/dev/null &&  echo 'EXISTS' || echo 'ERROR'"`
+    ret=$(sshpass -p $client_pass  $ssh  root@$host "id -u $user 2>&1 >/dev/null &&  echo 'EXISTS' || echo 'ERROR'")
     log WARN "The return value if $user exist is: $ret"
     if [[ "$ret" == "EXISTS"  || "$ret" == "" ]]; then
       
-      `sshpass -p $client_pass  $ssh  root@$host "echo $t | chpasswd  2>&1 /dev/null"`
+      sshpass -p $client_pass  $ssh  root@$host "echo $t | chpasswd  2>&1 /dev/null"
       if [ $? -eq 0 ]; then
         tableMiddle
       fi
@@ -223,20 +232,20 @@ linPassword () {
 
 
 winPassword () {
-  host_name=`nmblookup -A $host | grep '<00> -     '  | awk '{print $1}' | head -1`
+  host_name=$(nmblookup -A $host | grep '<00> -     '  | awk '{print $1}' | head -1)
   host_name=${host_name,,}
   log INFO "Customizing host $host_name , os $os"
-  Sn=`winexe  -U administrator%$oldroot //$host   "cmd /C wmic.exe bios get serialnumber <NUL:" | head -2 | tail -1`
+  Sn=$(winexe  -U administrator%$oldroot //$host   "cmd /C wmic.exe bios get serialnumber <NUL:" | head -2 | tail -1)
   comments=$Sn
-  line=`cat /tmp/pass.win.$random`
+  line=$(cat /tmp/pass.win.$random)
   OS="Windows"
   for t in $line; do
-    user=`echo $t | awk -F ":" '{print $1}'`
-    old_pass=`echo $t | awk -F ":" '{print $2}'`
-    new_pass=`echo $t | awk -F ":" '{print $3}'`
+    user=$(echo $t | awk -F ":" '{print $1}')
+    old_pass=$(echo $t | awk -F ":" '{print $2}')
+    new_pass=$(echo $t | awk -F ":" '{print $3}')
     tblpass=$new_pass
     log INFO "About tu run winexe -U $user%$old_pass //$host 'net user $user $new_pass'"
-    `winexe -U $user%$old_pass //$host "net user $user $new_pass" > /dev/null`
+    winexe -U $user%$old_pass //$host "net user $user $new_pass" > /dev/null
     if [ $? -eq 0 ]; then
       
       tableMiddle
@@ -349,8 +358,8 @@ do
 done
 
 # Set variables
-salesorder=`echo $so | awk -F "|" '{print $1}'`
-customerACR=`echo $so | awk -F "|" '{print $2}'`
+salesorder=$(echo $so | awk -F "|" '{print $1}')
+customerACR=$(echo $so | awk -F "|" '{print $2}')
 technology=" "
 customer=$customerACR
 region="  "
@@ -359,7 +368,7 @@ connection_type="  "
 site="  "
 pattern=" "
 comments=" "
-random=`date '+%s'`
+random=$(date '+%s')
 ssh="ssh -o GSSAPIAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet "
 #Set the tmp files to work on
 touch /tmp/mess.$random
