Updated error and logging functions

diff --git a/CCTPreparation/releaseDownload b/CCTPreparation/releaseDownload
--- a/CCTPreparation/releaseDownload
+++ b/CCTPreparation/releaseDownload
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #title          :releaseDownload
-#description    :prepare a full puppet server deployment
+#description    :download customer release in C:\Mycompany\Delivery
 #author         :ACS
 #date           :20160909
 #version        :1.1
@@ -10,8 +10,8 @@
 #@(#)------------------------------------------------------
 #@(#) General Information
 #@(#)   Name      : releaseDownload
-#@(#)   Purpose   : Aim to completely install a dedicated puppet server
-#@(#)   Version  ( : 1.1
+#@(#)   Purpose   : Aim to completely download customer release in C:\Mycompany\Delivery
+#@(#)   Version   : 1.1
 #@(#)   Author    : A. Cristalli
 #@(#)------------------------------------------------------
 #@(#) Usage
@@ -31,7 +31,7 @@ typeset SAMBACMD="$(which smbclient ) "
 typeset APISERVER="spmgt.my.comp.ltd"
 typeset SHARENAME='c$' 
 typeset MESSAGE="<div class='alert alert-danger blinking'>Executing $PROGNAME ..... Be patience</div>"
-
+PID=$$
 ## Parse prog name to find an ID if executed from SPOTDB
 
 ID=$(echo $PROGNAME | awk -F "_" '{print $3}')
@@ -149,7 +149,7 @@ log() {
         }
         
         Error() {
-            Help $0; exit $1
+            Help $0; exit $1; kill $PID
         }
         [ $# -eq 0 ] && Error 255
         while [ $# -gt 0 ] ; do
@@ -180,12 +180,13 @@ log() {
         fi
         hostNAME=$(nmblookup -A $MGT | grep '<00> -     '  | awk '{print $1}' | head -1)
   	hostNAME=${hostNAME,,}
+        MESSAGE="<div class='alert alert-danger blinking'>$hostNAME : Executing $PROGNAME ..... Be patience</div>" && log INFO "Starting the core of the script"
     }
     
     validateRelease () {
         ls $RELEASE 2>/dev/null
         if [ $? -ne 0 ]; then
-            MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" &&   log ERROR "The release $RELESE doesn't exist!" && exit 2
+            MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" &&   log ERROR "The release $RELESE doesn't exist!" && exit 2 && kill $PID
         fi
     }
      logCommand () {
@@ -212,7 +213,7 @@ log() {
 SMBCLIENTCOMMANDS
 
         if [ $? -ne 0 ]; then
-            MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>"  && echo "Cannot copy the release..." && exit 2
+            MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>"  && echo "Cannot copy the release..." && exit 2 && kill $PID
         fi
     }
  
@@ -222,12 +223,12 @@ SMBCLIENTCOMMANDS
   check=$(nmap -PN -p 139 $MGT | grep 'open')
   if [[ $check ==  "" ]]; then
      MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>"
-    log ERROR "Cannot connect to $MGT, samba port not open or host not reachable. Please, check  ip address, routing, or samba service available on remote host. " && exit 299
+    log ERROR "Cannot connect to $MGT, samba port not open or host not reachable. Please, check  ip address, routing, or samba service available on remote host. " && exit 299 && kill $PID
   fi
 
         # the following steps are self explanatory....
         validateRelease
 	 log WARN "Copying $RELEASE in //$MGT/$DELIVERY .... May takes some time."
         copyRelease 
-       MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" &&  log INFO "End of script execution"
+       MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" &&  log INFO "End of script execution"
       exit 0
diff --git a/Puppet/puppetInstall b/Puppet/puppetInstall
--- a/Puppet/puppetInstall
+++ b/Puppet/puppetInstall
@@ -38,7 +38,7 @@ typeset CIFSPKG="cifs-utils"
 typeset INSTALLCMD="/usr/share/nagra-foreman-installer/install.sh"
 typeset APISERVER="spmgt.my.comp.ltd"
 typeset MESSAGE="<div class='alert alert-danger blinking'>Executing Puppet installation ..... Be patience</div>"
-
+typeset PID=$$
 
 
 APISERVER=$(dig +short ${APISERVER})
@@ -163,7 +163,7 @@ _HERE_
         }
         
         Error() {
-            Help $0; exit $1
+            Help $0; exit $1 ; kill $PID
         }
         [ $# -eq 0 ] && Error 255
         while [ $# -gt 0 ] ; do
@@ -194,9 +194,10 @@ _HERE_
         [ $# -ne 0 ] && Error 255
         [[ -z $PUPPET || -z $RELEASE  || -z $GATEWAY ]] && Error 255
         if ! Validip $PUPPET  ; then
-             MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "$PUPPET Not a valid IP" && Error 255
+             MESSAGE="<div class='alert alert-success'>$PUPPET : $PROGNAME terminated</div>" && log ERROR "$PUPPET Not a valid IP" && Error 255
         fi
-        hostNAME=$(sshExe hostname )
+        hostNAME=$(sshExe "hostname" )
+	MESSAGE="<div class='alert alert-danger blinking'>$hostNAME : Executing Puppet installation ..... Be patience</div>" &&  log INFO "Starting core execution..."
     }
 
     logCommand () {
@@ -211,15 +212,19 @@ _HERE_
         # "$@" command or function
         test=$(nmap $PUPPET -PN -p ssh | grep open)
         if [[ "$test" == "" ]]; then
-             MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "Cannot contact the server $PUPPET, check the connection. Check also the correctness of the default route on $PUPPET"
-             exit 2
+             MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" && log ERROR "Cannot contact the server $PUPPET, check the connection. Check also the correctness of the default route on $PUPPET"
+             kill $PID && exit 137
         fi
-        sshpass -p  $ROOTPWD ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null  -t root@$PUPPET " $@"
+        local RESULT
+        RESULT=$(sshpass -p  $ROOTPWD ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null  -t root@$PUPPET " $@ 2>&1" 2>&1)
         if [[ $? -ne 0 ]]
         then
             log ERROR "There was an error running the command. I give up."
-             MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "$@"
-             exit 2
+             MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" && log ERROR "$@ $RESULT"
+             kill $PID && exit 137
+        else
+	    log COPY $RESULT
+	    echo $RESULT
         fi
     }
     
@@ -227,14 +232,14 @@ _HERE_
         # $1 source $2 destination
         test=$(nmap $PUPPET -PN -p ssh | grep open)
         if [[ "$test" == "" ]]; then
-            MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "Cannot contact the server $PUPPET, check the connection. Check also the correctness of the default route on $PUPPET"
-            exit 2
+            MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" && log ERROR "Cannot contact the server $PUPPET, check the connection. Check also the correctness of the default route on $PUPPET"
+            kill $PID && exit 137
         fi
         sshpass -p  $ROOTPWD scp -r -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null   "$1" root@$PUPPET:"$2"
         if [[ $? -ne 0 ]]
         then
-            MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "There was an error copying $iso . I give up."
-            exit 299
+            MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" && log ERROR "There was an error copying $iso . I give up."
+            kill $PID && exit 137
         fi
     }
     
@@ -243,7 +248,7 @@ _HERE_
         log WARN "trying to find release $RELESE"
         RES=$($FIND $PACKAGER $OPTIONS $RELEASE)
         if [[ "$RES" == "" ]]; then
-            MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "Release not found..." && exit 2
+            MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" && log ERROR "Release not found..." && kill $PID && exit 137
         else
             log INFO "Release $RES found!"
         fi
@@ -254,7 +259,7 @@ _HERE_
         log WARN "trying to find iso files....  "
         RES=$($FIND $RELPATH | grep  .iso)
         if [[ "$RES" == "" ]]; then
-            MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "No iso files to upload on server...." && exit 2
+            MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" && log ERROR "No iso files to upload on server...." && kill $PID && exit 137
         else
             log INFO "Iso files found : $RES"
         fi
@@ -265,7 +270,7 @@ _HERE_
         log WARN "trying to find mlds core module "
         RES=$($FIND $RELPATH -name 'MLDS_*' -print -quit)
         if [[ "$RES" == "" ]]; then
-            MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "MLDS module  not found" && exit 2
+            MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" && log ERROR "MLDS module  not found" && kill $PID && exit 137
         else
             log INFO "MLDS CORE found: $RES"
         fi
@@ -276,7 +281,7 @@ _HERE_
         log WARN "Going to install puppet and foreman.... "
         RPMS=$($FIND $MLDSCOREPATH -name '*.rpm')
         if [[ "$RPMS" == "" ]]; then
-            MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" && log ERROR "RPMS  not found" && exit 2
+            MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" && log ERROR "RPMS  not found" && kill $PID && exit 137
         else
             log INFO "RPMS CORE found! "
             log WARN "Going to install them and prepare the environment"
@@ -322,7 +327,7 @@ _HERE_
     #Test if the remote host can be reached
   check=$(nmap -PN -p ssh $PUPPET | grep 'open')
   if [[ $check ==  "" ]]; then
-     MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>"
+     MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>"
     log ERROR "Cannot connect to $PUPPET, ssh port not open or host not reachable. Please, check  ip address, routing, or ssh service available on remote host. "
     error_exit
   fi
@@ -338,7 +343,7 @@ _HERE_
     mountPackager
     addRelease | logCommand
     
-   MESSAGE="<div class='alert alert-success'>$PROGNAME terminated</div>" &&  log INFO "End of script execution"
+   MESSAGE="<div class='alert alert-success'>$hostNAME : $PROGNAME terminated</div>" &&  log INFO "End of script execution"
     exit 0
     
     
